/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
  serializers.chatHistory.messageGetChatHistory.Response.Raw,
  SugarAiApi.MessageGetChatHistoryResponseItem[]
> = core.serialization.list(
  core.serialization.lazyObject(
    async () => (await import("../../..")).MessageGetChatHistoryResponseItem,
  ),
);

export declare namespace Response {
  type Raw = serializers.MessageGetChatHistoryResponseItem.Raw[];
}
