/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
  serializers.embedding.lookup.Response.Raw,
  SugarAiApi.EmbeddingLookupResponseItem[]
> = core.serialization.list(
  core.serialization.lazyObject(
    async () => (await import("../../..")).EmbeddingLookupResponseItem,
  ),
);

export declare namespace Response {
  type Raw = serializers.EmbeddingLookupResponseItem.Raw[];
}
