/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

/**
 * @example
 *     {
 *         scope: {
 *             clientUserId: "clientUserId"
 *         },
 *         userQuery: "userQuery"
 *     }
 */
export interface EmbeddingLookupRequest {
  userId?: string;
  scope: SugarAiApi.EmbeddingLookupRequestScope;
  userQuery: string;
}
