/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChatGenerateChatResponseCopilotId {
  copilotId: string;
  messageCount?: number;
  id: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}
