/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const EmbeddingLookupRequest: core.serialization.Schema<
  serializers.EmbeddingLookupRequest.Raw,
  SugarAiApi.EmbeddingLookupRequest
> = core.serialization.object({
  userId: core.serialization.string().optional(),
  scope: core.serialization.lazyObject(
    async () => (await import("../../../..")).EmbeddingLookupRequestScope,
  ),
  userQuery: core.serialization.string(),
});

export declare namespace EmbeddingLookupRequest {
  interface Raw {
    userId?: string | null;
    scope: serializers.EmbeddingLookupRequestScope.Raw;
    userQuery: string;
  }
}
