/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const EmbeddingCreateOrUpdateRequest: core.serialization.Schema<
  serializers.EmbeddingCreateOrUpdateRequest.Raw,
  SugarAiApi.EmbeddingCreateOrUpdateRequest
> = core.serialization.object({
  scope: core.serialization.lazyObject(
    async () =>
      (await import("../../../..")).EmbeddingCreateOrUpdateRequestScope,
  ),
  payload: core.serialization.unknown().optional(),
  strategy: core.serialization.string().optional(),
});

export declare namespace EmbeddingCreateOrUpdateRequest {
  interface Raw {
    scope: serializers.EmbeddingCreateOrUpdateRequestScope.Raw;
    payload?: unknown | null;
    strategy?: string | null;
  }
}
