/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ChatGenerateChatResponseCopilotId: core.serialization.ObjectSchema<
  serializers.ChatGenerateChatResponseCopilotId.Raw,
  SugarAiApi.ChatGenerateChatResponseCopilotId
> = core.serialization.object({
  copilotId: core.serialization.string(),
  messageCount: core.serialization.number().optional(),
  id: core.serialization.string(),
  userId: core.serialization.string(),
  createdAt: core.serialization.date(),
  updatedAt: core.serialization.date(),
});

export declare namespace ChatGenerateChatResponseCopilotId {
  interface Raw {
    copilotId: string;
    messageCount?: number | null;
    id: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
  }
}
