/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ChatGenerateChatResponse: core.serialization.Schema<
  serializers.ChatGenerateChatResponse.Raw,
  SugarAiApi.ChatGenerateChatResponse
> = core.serialization.undiscriminatedUnion([
  core.serialization.lazyObject(
    async () => (await import("../../..")).ChatGenerateChatResponseCopilotId,
  ),
  core.serialization.stringLiteral("null"),
]);

export declare namespace ChatGenerateChatResponse {
  type Raw = serializers.ChatGenerateChatResponseCopilotId.Raw | "null";
}
