/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const MessageGenerateMessageRequest: core.serialization.Schema<
  serializers.MessageGenerateMessageRequest.Raw,
  SugarAiApi.MessageGenerateMessageRequest
> = core.serialization.object({
  logId: core.serialization.string().optional(),
  content: core.serialization.string(),
  role: core.serialization.lazy(
    async () => (await import("../../../..")).MessageGenerateMessageRequestRole,
  ),
  metadata: core.serialization
    .lazy(
      async () =>
        (await import("../../../..")).MessageGenerateMessageRequestMetadata,
    )
    .optional(),
});

export declare namespace MessageGenerateMessageRequest {
  interface Raw {
    logId?: string | null;
    content: string;
    role: serializers.MessageGenerateMessageRequestRole.Raw;
    metadata?: serializers.MessageGenerateMessageRequestMetadata.Raw | null;
  }
}
