/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export type PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersion =
  | SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionZero
  | Record<string, unknown>;
