/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

export interface MessageGenerateMessageRequest {
  logId?: string;
  content: string;
  role: SugarAiApi.MessageGenerateMessageRequestRole;
  metadata?: SugarAiApi.MessageGenerateMessageRequestMetadata;
}
