/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmbeddingLookupRequestScope {
  clientUserId: string;
  scope1?: string;
  scope2?: string;
  groupId?: string;
}
