/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SugarAiApiEnvironment = {
  Default: "https://api.sugarcaneai.dev/api",
} as const;

export type SugarAiApiEnvironment = typeof SugarAiApiEnvironment.Default;
