/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionZero: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionZero.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionZero
> = core.serialization.undiscriminatedUnion([
  core.serialization.unknown(),
  core.serialization.stringLiteral("null"),
]);

export declare namespace PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionZero {
  type Raw = unknown | "null";
}
