/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtVisibility: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItemCreatedAtVisibility.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtVisibility
> = core.serialization.enum_(["PUBLIC", "PRIVATE"]);

export declare namespace PromptGetPackagesResponseItemCreatedAtVisibility {
  type Raw = "PUBLIC" | "PRIVATE";
}
