/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAt: core.serialization.ObjectSchema<
  serializers.PromptGetPackagesResponseItemCreatedAt.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAt
> = core.serialization.object({
  id: core.serialization.string(),
  userId: core.serialization.string(),
  name: core.serialization.string(),
  visibility: core.serialization.lazy(
    async () =>
      (await import("../../.."))
        .PromptGetPackagesResponseItemCreatedAtVisibility,
  ),
  description: core.serialization.string(),
  createdAt: core.serialization.date(),
  updatedAt: core.serialization.date(),
  templates: core.serialization
    .list(
      core.serialization.lazyObject(
        async () =>
          (await import("../../.."))
            .PromptGetPackagesResponseItemCreatedAtTemplatesItem,
      ),
    )
    .optional(),
});

export declare namespace PromptGetPackagesResponseItemCreatedAt {
  interface Raw {
    id: string;
    userId: string;
    name: string;
    visibility: serializers.PromptGetPackagesResponseItemCreatedAtVisibility.Raw;
    description: string;
    createdAt: string;
    updatedAt: string;
    templates?:
      | serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItem.Raw[]
      | null;
  }
}
