/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion
> = core.serialization.undiscriminatedUnion([
  core.serialization.lazy(
    async () =>
      (await import("../../.."))
        .PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionZero,
  ),
  core.serialization.record(
    core.serialization.string(),
    core.serialization.unknown(),
  ),
]);

export declare namespace PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion {
  type Raw =
    | serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionZero.Raw
    | Record<string, unknown>;
}
