/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId
> = core.serialization.undiscriminatedUnion([
  core.serialization.string(),
  core.serialization.stringLiteral("null"),
]);

export declare namespace PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId {
  type Raw = string | "null";
}
