/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const MessageGetChatHistoryResponseItemRole: core.serialization.Schema<
  serializers.MessageGetChatHistoryResponseItemRole.Raw,
  SugarAiApi.MessageGetChatHistoryResponseItemRole
> = core.serialization.enum_(["user", "assistant", "system"]);

export declare namespace MessageGetChatHistoryResponseItemRole {
  type Raw = "user" | "assistant" | "system";
}
