/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormSubmissionSubmitAnswerRequestAnswerBy: core.serialization.Schema<
  serializers.FormSubmissionSubmitAnswerRequestAnswerBy.Raw,
  SugarAiApi.FormSubmissionSubmitAnswerRequestAnswerBy
> = core.serialization.enum_(["voice", "manual"]);

export declare namespace FormSubmissionSubmitAnswerRequestAnswerBy {
  type Raw = "voice" | "manual";
}
