/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormSubmissionCompleteSubmissionResponse: core.serialization.ObjectSchema<
  serializers.FormSubmissionCompleteSubmissionResponse.Raw,
  SugarAiApi.FormSubmissionCompleteSubmissionResponse
> = core.serialization.object({
  submissionId: core.serialization.string(),
  message: core.serialization.string(),
});

export declare namespace FormSubmissionCompleteSubmissionResponse {
  interface Raw {
    submissionId: string;
    message: string;
  }
}
