/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormGetSubmissionResponseAnswersItem: core.serialization.ObjectSchema<
  serializers.FormGetSubmissionResponseAnswersItem.Raw,
  SugarAiApi.FormGetSubmissionResponseAnswersItem
> = core.serialization.object({
  questionId: core.serialization.string(),
  answer: core.serialization.unknown().optional(),
  metadata: core.serialization.lazy(
    async () =>
      (await import("../../..")).FormGetSubmissionResponseAnswersItemMetadata,
  ),
  updatedAt: core.serialization.date(),
  createdAt: core.serialization.date(),
});

export declare namespace FormGetSubmissionResponseAnswersItem {
  interface Raw {
    questionId: string;
    answer?: unknown | null;
    metadata: serializers.FormGetSubmissionResponseAnswersItemMetadata.Raw;
    updatedAt: string;
    createdAt: string;
  }
}
