/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormSubmissionSubmitAnswerResponse: core.serialization.ObjectSchema<
  serializers.FormSubmissionSubmitAnswerResponse.Raw,
  SugarAiApi.FormSubmissionSubmitAnswerResponse
> = core.serialization.object({
  id: core.serialization.string(),
});

export declare namespace FormSubmissionSubmitAnswerResponse {
  interface Raw {
    id: string;
  }
}
