/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormSubmissionCreateSubmissionResponse: core.serialization.ObjectSchema<
  serializers.FormSubmissionCreateSubmissionResponse.Raw,
  SugarAiApi.FormSubmissionCreateSubmissionResponse
> = core.serialization.object({
  submissionId: core.serialization.string(),
});

export declare namespace FormSubmissionCreateSubmissionResponse {
  interface Raw {
    submissionId: string;
  }
}
