/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormSubmissionSubmitAnswerRequestAnswerRecording: core.serialization.ObjectSchema<
  serializers.FormSubmissionSubmitAnswerRequestAnswerRecording.Raw,
  SugarAiApi.FormSubmissionSubmitAnswerRequestAnswerRecording
> = core.serialization.object({
  audioUrl: core.serialization.string(),
  audioFile: core.serialization.unknown(),
});

export declare namespace FormSubmissionSubmitAnswerRequestAnswerRecording {
  interface Raw {
    audioUrl: string;
    audioFile?: unknown;
  }
}
