/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const FormSubmissionSubmitAnswerRequestMetadata: core.serialization.Schema<
  serializers.FormSubmissionSubmitAnswerRequestMetadata.Raw,
  SugarAiApi.FormSubmissionSubmitAnswerRequestMetadata
> = core.serialization.undiscriminatedUnion([
  core.serialization.string(),
  core.serialization.number(),
  core.serialization.boolean(),
  core.serialization.list(core.serialization.unknown()),
  core.serialization.record(
    core.serialization.string(),
    core.serialization.unknown(),
  ),
]);

export declare namespace FormSubmissionSubmitAnswerRequestMetadata {
  type Raw = string | number | boolean | unknown[] | Record<string, unknown>;
}
