/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestMessagesItemRole: core.serialization.Schema<
  serializers.LiteServiceGenerateRequestMessagesItemRole.Raw,
  SugarAiApi.LiteServiceGenerateRequestMessagesItemRole
> = core.serialization.enum_(["user", "assistant", "system", "tool"]);

export declare namespace LiteServiceGenerateRequestMessagesItemRole {
  type Raw = "user" | "assistant" | "system" | "tool";
}
