/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestEnvironment: core.serialization.Schema<
  serializers.LiteServiceGenerateRequestEnvironment.Raw,
  SugarAiApi.LiteServiceGenerateRequestEnvironment
> = core.serialization.enum_(["DEV", "PREVIEW", "RELEASE"]);

export declare namespace LiteServiceGenerateRequestEnvironment {
  type Raw = "DEV" | "PREVIEW" | "RELEASE";
}
