/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestMessagesItem: core.serialization.ObjectSchema<
  serializers.ServiceGenerateRequestMessagesItem.Raw,
  SugarAiApi.ServiceGenerateRequestMessagesItem
> = core.serialization.object({
  role: core.serialization.lazy(
    async () =>
      (await import("../../..")).ServiceGenerateRequestMessagesItemRole,
  ),
  content: core.serialization.string(),
});

export declare namespace ServiceGenerateRequestMessagesItem {
  interface Raw {
    role: serializers.ServiceGenerateRequestMessagesItemRole.Raw;
    content: string;
  }
}
