/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateResponseCompletionEnvironment: core.serialization.Schema<
  serializers.ServiceGenerateResponseCompletionEnvironment.Raw,
  SugarAiApi.ServiceGenerateResponseCompletionEnvironment
> = core.serialization.enum_(["DEV", "PREVIEW", "RELEASE"]);

export declare namespace ServiceGenerateResponseCompletionEnvironment {
  type Raw = "DEV" | "PREVIEW" | "RELEASE";
}
