/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateResponse: core.serialization.Schema<
  serializers.ServiceGenerateResponse.Raw,
  SugarAiApi.ServiceGenerateResponse
> = core.serialization.undiscriminatedUnion([
  core.serialization.lazyObject(
    async () => (await import("../../..")).ServiceGenerateResponseCompletion,
  ),
  core.serialization.stringLiteral("null"),
]);

export declare namespace ServiceGenerateResponse {
  type Raw = serializers.ServiceGenerateResponseCompletion.Raw | "null";
}
