/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestSkillChoice: core.serialization.Schema<
  serializers.ServiceGenerateRequestSkillChoice.Raw,
  SugarAiApi.ServiceGenerateRequestSkillChoice
> = core.serialization.enum_(["auto", "none"]);

export declare namespace ServiceGenerateRequestSkillChoice {
  type Raw = "auto" | "none";
}
