/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue: core.serialization.ObjectSchema<
  serializers.ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue.Raw,
  SugarAiApi.ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue
> = core.serialization.object({
  type: core.serialization.string(),
  description: core.serialization.string(),
  enum: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue {
  interface Raw {
    type: string;
    description: string;
    enum?: string[] | null;
  }
}
