/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateResponseCompletionLabelledState: core.serialization.Schema<
  serializers.ServiceGenerateResponseCompletionLabelledState.Raw,
  SugarAiApi.ServiceGenerateResponseCompletionLabelledState
> = core.serialization.enum_(["UNLABELLED", "SELECTED", "REJECTED", "NOTSURE"]);

export declare namespace ServiceGenerateResponseCompletionLabelledState {
  type Raw = "UNLABELLED" | "SELECTED" | "REJECTED" | "NOTSURE";
}
