/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageGenerateMessageRequestRole = "user" | "assistant" | "system";

export const MessageGenerateMessageRequestRole = {
  User: "user",
  Assistant: "assistant",
  System: "system",
} as const;
