/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface MessageGenerateMessageResponseChatId {
  copilotId: string;
  logId?: string;
  content: string;
  role: SugarAiApi.MessageGenerateMessageResponseChatIdRole;
  chatId: string;
  metadata?: SugarAiApi.MessageGenerateMessageResponseChatIdMetadata;
  id: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}
