/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export type MessageGenerateMessageResponse =
  | SugarAiApi.MessageGenerateMessageResponseChatId
  | "null";
