/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageGenerateMessageResponseChatIdRole =
  | "user"
  | "assistant"
  | "system";

export const MessageGenerateMessageResponseChatIdRole = {
  User: "user",
  Assistant: "assistant",
  System: "system",
} as const;
