/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const ChatGenerateChatRequest: core.serialization.Schema<
  serializers.ChatGenerateChatRequest.Raw,
  SugarAiApi.ChatGenerateChatRequest
> = core.serialization.object({
  messageCount: core.serialization.number().optional(),
});

export declare namespace ChatGenerateChatRequest {
  interface Raw {
    messageCount?: number | null;
  }
}
