/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

export interface CubeGetPromptRequest {
  environment?: SugarAiApi.CubeGetPromptRequestEnvironment;
  version?: string;
  userId?: string;
  promptPackageId?: string;
  promptTemplateId?: string;
  promptVersionId?: string;
}
