/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

export interface LiteServiceGenerateRequest {
  variables: Record<string, unknown>;
  messages?: SugarAiApi.LiteServiceGenerateRequestMessagesItem[];
  attachments?: Record<string, unknown>;
  skills?: SugarAiApi.LiteServiceGenerateRequestSkillsItem[];
  skillChoice?: SugarAiApi.LiteServiceGenerateRequestSkillChoice;
  scope?: SugarAiApi.LiteServiceGenerateRequestScope;
  isDevelopment?: boolean;
  chat?: SugarAiApi.LiteServiceGenerateRequestChat;
  copilotId?: string;
  environment?: SugarAiApi.LiteServiceGenerateRequestEnvironment;
  version?: string;
  userId?: string;
  promptPackageId?: string;
  promptTemplateId?: string;
  promptVersionId?: string;
}
