/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId
> = core.serialization.undiscriminatedUnion([
  core.serialization.string(),
  core.serialization.stringLiteral("null"),
]);

export declare namespace PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId {
  type Raw = string | "null";
}
