/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionZero: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionZero.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionZero
> = core.serialization.undiscriminatedUnion([
  core.serialization.unknown(),
  core.serialization.stringLiteral("null"),
]);

export declare namespace PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionZero {
  type Raw = unknown | "null";
}
