/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItem: core.serialization.Schema<
  serializers.PromptGetPackagesResponseItem.Raw,
  SugarAiApi.PromptGetPackagesResponseItem
> = core.serialization.undiscriminatedUnion([
  core.serialization.lazyObject(
    async () =>
      (await import("../../..")).PromptGetPackagesResponseItemCreatedAt,
  ),
  core.serialization.stringLiteral("null"),
]);

export declare namespace PromptGetPackagesResponseItem {
  type Raw = serializers.PromptGetPackagesResponseItemCreatedAt.Raw | "null";
}
