/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesRequestVisibility: core.serialization.Schema<
  serializers.PromptGetPackagesRequestVisibility.Raw,
  SugarAiApi.PromptGetPackagesRequestVisibility
> = core.serialization.enum_(["PUBLIC", "PRIVATE"]);

export declare namespace PromptGetPackagesRequestVisibility {
  type Raw = "PUBLIC" | "PRIVATE";
}
