/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItem: core.serialization.ObjectSchema<
  serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItem.Raw,
  SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItem
> = core.serialization.object({
  id: core.serialization.string(),
  userId: core.serialization.string(),
  promptPackageId: core.serialization.string(),
  name: core.serialization.string(),
  description: core.serialization.string(),
  modelType: core.serialization.lazy(
    async () =>
      (await import("../../.."))
        .PromptGetPackagesResponseItemCreatedAtTemplatesItemModelType,
  ),
  runMode: core.serialization.lazy(
    async () =>
      (await import("../../.."))
        .PromptGetPackagesResponseItemCreatedAtTemplatesItemRunMode,
  ),
  releaseVersionId: core.serialization.lazy(
    async () =>
      (await import("../../.."))
        .PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId,
  ),
  previewVersionId: core.serialization.lazy(
    async () =>
      (await import("../../.."))
        .PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId,
  ),
  releaseVersion: core.serialization
    .lazy(
      async () =>
        (await import("../../.."))
          .PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersion,
    )
    .optional(),
  previewVersion: core.serialization
    .lazy(
      async () =>
        (await import("../../.."))
          .PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion,
    )
    .optional(),
  createdAt: core.serialization.date(),
  updatedAt: core.serialization.date(),
});

export declare namespace PromptGetPackagesResponseItemCreatedAtTemplatesItem {
  interface Raw {
    id: string;
    userId: string;
    promptPackageId: string;
    name: string;
    description: string;
    modelType: serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemModelType.Raw;
    runMode: serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemRunMode.Raw;
    releaseVersionId: serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId.Raw;
    previewVersionId: serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId.Raw;
    releaseVersion?: serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersion.Raw | null;
    previewVersion?: serializers.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion.Raw | null;
    createdAt: string;
    updatedAt: string;
  }
}
