/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const CubeGetPromptResponse: core.serialization.Schema<
  serializers.CubeGetPromptResponse.Raw,
  SugarAiApi.CubeGetPromptResponse
> = core.serialization.undiscriminatedUnion([
  core.serialization.lazyObject(
    async () => (await import("../../..")).CubeGetPromptResponseCreatedAt,
  ),
  core.serialization.stringLiteral("null"),
]);

export declare namespace CubeGetPromptResponse {
  type Raw = serializers.CubeGetPromptResponseCreatedAt.Raw | "null";
}
