/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const CubeGetPromptResponseCreatedAtRunMode: core.serialization.Schema<
  serializers.CubeGetPromptResponseCreatedAtRunMode.Raw,
  SugarAiApi.CubeGetPromptResponseCreatedAtRunMode
> = core.serialization.enum_(["AUTHORISED_ONLY", "LOGGEDIN_ONLY", "ALL"]);

export declare namespace CubeGetPromptResponseCreatedAtRunMode {
  type Raw = "AUTHORISED_ONLY" | "LOGGEDIN_ONLY" | "ALL";
}
