/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const CubeGetPromptResponseCreatedAt: core.serialization.ObjectSchema<
  serializers.CubeGetPromptResponseCreatedAt.Raw,
  SugarAiApi.CubeGetPromptResponseCreatedAt
> = core.serialization.object({
  version: core.serialization.string().optional(),
  template: core.serialization.string(),
  promptData: core.serialization.unknown().optional(),
  llmProvider: core.serialization.string(),
  model: core.serialization.string(),
  description: core.serialization.string().optional(),
  modelType: core.serialization.lazy(
    async () =>
      (await import("../../..")).CubeGetPromptResponseCreatedAtModelType,
  ),
  versionOrEnvironment: core.serialization.string().optional(),
  createdAt: core.serialization.date(),
  updatedAt: core.serialization.date(),
  promptPackageId: core.serialization.string(),
  templateId: core.serialization.string(),
  runMode: core.serialization.lazy(
    async () =>
      (await import("../../..")).CubeGetPromptResponseCreatedAtRunMode,
  ),
});

export declare namespace CubeGetPromptResponseCreatedAt {
  interface Raw {
    version?: string | null;
    template: string;
    promptData?: unknown | null;
    llmProvider: string;
    model: string;
    description?: string | null;
    modelType: serializers.CubeGetPromptResponseCreatedAtModelType.Raw;
    versionOrEnvironment?: string | null;
    createdAt: string;
    updatedAt: string;
    promptPackageId: string;
    templateId: string;
    runMode: serializers.CubeGetPromptResponseCreatedAtRunMode.Raw;
  }
}
