/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestSkillsItem: core.serialization.ObjectSchema<
  serializers.LiteServiceGenerateRequestSkillsItem.Raw,
  SugarAiApi.LiteServiceGenerateRequestSkillsItem
> = core.serialization.object({
  type: core.serialization.stringLiteral("function"),
  function: core.serialization.lazyObject(
    async () =>
      (await import("../../..")).LiteServiceGenerateRequestSkillsItemFunction,
  ),
});

export declare namespace LiteServiceGenerateRequestSkillsItem {
  interface Raw {
    type: "function";
    function: serializers.LiteServiceGenerateRequestSkillsItemFunction.Raw;
  }
}
