/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestRouter: core.serialization.ObjectSchema<
  serializers.LiteServiceGenerateRequestRouter.Raw,
  SugarAiApi.LiteServiceGenerateRequestRouter
> = core.serialization.object({
  mode: core.serialization
    .lazy(
      async () =>
        (await import("../../..")).LiteServiceGenerateRequestRouterMode,
    )
    .optional(),
  threshold: core.serialization.number().optional(),
});

export declare namespace LiteServiceGenerateRequestRouter {
  interface Raw {
    mode?: serializers.LiteServiceGenerateRequestRouterMode.Raw | null;
    threshold?: number | null;
  }
}
