/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateResponseChatRouter: core.serialization.ObjectSchema<
  serializers.LiteServiceGenerateResponseChatRouter.Raw,
  SugarAiApi.LiteServiceGenerateResponseChatRouter
> = core.serialization.object({
  mode: core.serialization.lazy(
    async () =>
      (await import("../../..")).LiteServiceGenerateResponseChatRouterMode,
  ),
  match: core.serialization.string(),
  prompt: core.serialization.string(),
  score: core.serialization.number(),
  threshold: core.serialization.number(),
  text: core.serialization.string(),
});

export declare namespace LiteServiceGenerateResponseChatRouter {
  interface Raw {
    mode: serializers.LiteServiceGenerateResponseChatRouterMode.Raw;
    match: string;
    prompt: string;
    score: number;
    threshold: number;
    text: string;
  }
}
