/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateResponseChatRouterMode: core.serialization.Schema<
  serializers.LiteServiceGenerateResponseChatRouterMode.Raw,
  SugarAiApi.LiteServiceGenerateResponseChatRouterMode
> = core.serialization.enum_(["auto", "manual"]);

export declare namespace LiteServiceGenerateResponseChatRouterMode {
  type Raw = "auto" | "manual";
}
