/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateResponseChat: core.serialization.ObjectSchema<
  serializers.LiteServiceGenerateResponseChat.Raw,
  SugarAiApi.LiteServiceGenerateResponseChat
> = core.serialization.object({
  llmResponse: core.serialization
    .lazy(
      async () =>
        (await import("../../..")).LiteServiceGenerateResponseChatLlmResponse,
    )
    .optional(),
  chat: core.serialization
    .lazy(
      async () =>
        (await import("../../..")).LiteServiceGenerateResponseChatChat,
    )
    .optional(),
  stats: core.serialization
    .lazy(
      async () =>
        (await import("../../..")).LiteServiceGenerateResponseChatStats,
    )
    .optional(),
});

export declare namespace LiteServiceGenerateResponseChat {
  interface Raw {
    llmResponse?: serializers.LiteServiceGenerateResponseChatLlmResponse.Raw | null;
    chat?: serializers.LiteServiceGenerateResponseChatChat.Raw | null;
    stats?: serializers.LiteServiceGenerateResponseChatStats.Raw | null;
  }
}
