/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestSkillChoice: core.serialization.Schema<
  serializers.LiteServiceGenerateRequestSkillChoice.Raw,
  SugarAiApi.LiteServiceGenerateRequestSkillChoice
> = core.serialization.enum_(["auto", "none"]);

export declare namespace LiteServiceGenerateRequestSkillChoice {
  type Raw = "auto" | "none";
}
