/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestChatMessage: core.serialization.ObjectSchema<
  serializers.LiteServiceGenerateRequestChatMessage.Raw,
  SugarAiApi.LiteServiceGenerateRequestChatMessage
> = core.serialization.object({
  role: core.serialization.lazy(
    async () =>
      (await import("../../..")).LiteServiceGenerateRequestChatMessageRole,
  ),
  content: core.serialization.string(),
});

export declare namespace LiteServiceGenerateRequestChatMessage {
  interface Raw {
    role: serializers.LiteServiceGenerateRequestChatMessageRole.Raw;
    content: string;
  }
}
