/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateRequestRouterMode: core.serialization.Schema<
  serializers.LiteServiceGenerateRequestRouterMode.Raw,
  SugarAiApi.LiteServiceGenerateRequestRouterMode
> = core.serialization.enum_(["auto", "manual"]);

export declare namespace LiteServiceGenerateRequestRouterMode {
  type Raw = "auto" | "manual";
}
