/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const LiteServiceGenerateResponse: core.serialization.Schema<
  serializers.LiteServiceGenerateResponse.Raw,
  SugarAiApi.LiteServiceGenerateResponse
> = core.serialization.undiscriminatedUnion([
  core.serialization.lazyObject(
    async () => (await import("../../..")).LiteServiceGenerateResponseChat,
  ),
  core.serialization.stringLiteral("null"),
]);

export declare namespace LiteServiceGenerateResponse {
  type Raw = serializers.LiteServiceGenerateResponseChat.Raw | "null";
}
