/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateResponseChatLabelledState: core.serialization.Schema<
  serializers.ServiceGenerateResponseChatLabelledState.Raw,
  SugarAiApi.ServiceGenerateResponseChatLabelledState
> = core.serialization.enum_(["UNLABELLED", "SELECTED", "REJECTED", "NOTSURE"]);

export declare namespace ServiceGenerateResponseChatLabelledState {
  type Raw = "UNLABELLED" | "SELECTED" | "REJECTED" | "NOTSURE";
}
