/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestChatMessageRole: core.serialization.Schema<
  serializers.ServiceGenerateRequestChatMessageRole.Raw,
  SugarAiApi.ServiceGenerateRequestChatMessageRole
> = core.serialization.enum_(["user", "assistant", "system", "tool"]);

export declare namespace ServiceGenerateRequestChatMessageRole {
  type Raw = "user" | "assistant" | "system" | "tool";
}
