/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestSkillsItemFunctionParameters: core.serialization.ObjectSchema<
  serializers.ServiceGenerateRequestSkillsItemFunctionParameters.Raw,
  SugarAiApi.ServiceGenerateRequestSkillsItemFunctionParameters
> = core.serialization.object({
  type: core.serialization.string(),
  properties: core.serialization.record(
    core.serialization.string(),
    core.serialization.lazyObject(
      async () =>
        (await import("../../.."))
          .ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue,
    ),
  ),
  required: core.serialization.list(core.serialization.string()),
});

export declare namespace ServiceGenerateRequestSkillsItemFunctionParameters {
  interface Raw {
    type: string;
    properties: Record<
      string,
      serializers.ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue.Raw
    >;
    required: string[];
  }
}
