/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestRouter: core.serialization.ObjectSchema<
  serializers.ServiceGenerateRequestRouter.Raw,
  SugarAiApi.ServiceGenerateRequestRouter
> = core.serialization.object({
  mode: core.serialization
    .lazy(
      async () => (await import("../../..")).ServiceGenerateRequestRouterMode,
    )
    .optional(),
  threshold: core.serialization.number().optional(),
});

export declare namespace ServiceGenerateRequestRouter {
  interface Raw {
    mode?: serializers.ServiceGenerateRequestRouterMode.Raw | null;
    threshold?: number | null;
  }
}
