/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestMessagesItemRole: core.serialization.Schema<
  serializers.ServiceGenerateRequestMessagesItemRole.Raw,
  SugarAiApi.ServiceGenerateRequestMessagesItemRole
> = core.serialization.enum_(["user", "assistant", "system", "tool"]);

export declare namespace ServiceGenerateRequestMessagesItemRole {
  type Raw = "user" | "assistant" | "system" | "tool";
}
