/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestSkillsItem: core.serialization.ObjectSchema<
  serializers.ServiceGenerateRequestSkillsItem.Raw,
  SugarAiApi.ServiceGenerateRequestSkillsItem
> = core.serialization.object({
  type: core.serialization.stringLiteral("function"),
  function: core.serialization.lazyObject(
    async () =>
      (await import("../../..")).ServiceGenerateRequestSkillsItemFunction,
  ),
});

export declare namespace ServiceGenerateRequestSkillsItem {
  interface Raw {
    type: "function";
    function: serializers.ServiceGenerateRequestSkillsItemFunction.Raw;
  }
}
