/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const ServiceGenerateRequestRouterMode: core.serialization.Schema<
  serializers.ServiceGenerateRequestRouterMode.Raw,
  SugarAiApi.ServiceGenerateRequestRouterMode
> = core.serialization.enum_(["auto", "manual"]);

export declare namespace ServiceGenerateRequestRouterMode {
  type Raw = "auto" | "manual";
}
