/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const EmbeddingCreateOrUpdateResponse: core.serialization.ObjectSchema<
  serializers.EmbeddingCreateOrUpdateResponse.Raw,
  SugarAiApi.EmbeddingCreateOrUpdateResponse
> = core.serialization.object({
  count: core.serialization.number(),
  strategy: core.serialization.string().optional(),
});

export declare namespace EmbeddingCreateOrUpdateResponse {
  interface Raw {
    count: number;
    strategy?: string | null;
  }
}
