/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormSubmissionSubmitAnswerRequestAnswerBy =
  | "voice"
  | "keyboard"
  | "document";

export const FormSubmissionSubmitAnswerRequestAnswerBy = {
  Voice: "voice",
  Keyboard: "keyboard",
  Document: "document",
} as const;
