/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormSubmissionSubmitAnswerRequestAnswerBy = "voice" | "manual";

export const FormSubmissionSubmitAnswerRequestAnswerBy = {
  Voice: "voice",
  Manual: "manual",
} as const;
