/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormSubmissionSubmitAnswerRequestAnswerBy = "voice" | "keyboard";

export const FormSubmissionSubmitAnswerRequestAnswerBy = {
  Voice: "voice",
  Keyboard: "keyboard",
} as const;
