/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface FormGetSubmissionResponseAnswersItem {
  questionId: string;
  answer?: unknown;
  metadata: SugarAiApi.FormGetSubmissionResponseAnswersItemMetadata;
  updatedAt: Date;
  createdAt: Date;
}
