/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface MessageGetChatHistoryResponseItem {
  copilotId: string;
  logId?: string;
  content: string;
  role: SugarAiApi.MessageGetChatHistoryResponseItemRole;
  chatId: string;
  metadata?: SugarAiApi.MessageGetChatHistoryResponseItemMetadata;
  id: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}
