/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
  serializers.packages.promptGetPackages.Response.Raw,
  SugarAiApi.PromptGetPackagesResponseItem[]
> = core.serialization.list(
  core.serialization.lazy(
    async () => (await import("../../..")).PromptGetPackagesResponseItem,
  ),
);

export declare namespace Response {
  type Raw = serializers.PromptGetPackagesResponseItem.Raw[];
}
