/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface CubeGetPromptResponseCreatedAt {
  version?: string;
  template: string;
  promptData?: unknown;
  llmProvider: string;
  model: string;
  description?: string;
  modelType: SugarAiApi.CubeGetPromptResponseCreatedAtModelType;
  versionOrEnvironment?: string;
  createdAt: Date;
  updatedAt: Date;
  promptPackageId: string;
  templateId: string;
  runMode: SugarAiApi.CubeGetPromptResponseCreatedAtRunMode;
}
