/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CubeGetPromptResponseCreatedAtRunMode =
  | "AUTHORISED_ONLY"
  | "LOGGEDIN_ONLY"
  | "ALL";

export const CubeGetPromptResponseCreatedAtRunMode = {
  AuthorisedOnly: "AUTHORISED_ONLY",
  LoggedinOnly: "LOGGEDIN_ONLY",
  All: "ALL",
} as const;
