/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateRequestChat {
  id?: string;
  message?: SugarAiApi.LiteServiceGenerateRequestChatMessage;
  historyChat?: number;
}
