/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LiteServiceGenerateRequestMessagesItemRole =
  | "user"
  | "assistant"
  | "system"
  | "tool";

export const LiteServiceGenerateRequestMessagesItemRole = {
  User: "user",
  Assistant: "assistant",
  System: "system",
  Tool: "tool",
} as const;
