/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateRequestSkillsItemFunction {
  name: string;
  description: string;
  parameters: SugarAiApi.LiteServiceGenerateRequestSkillsItemFunctionParameters;
}
