/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateResponseChat {
  llmResponse?: SugarAiApi.ServiceGenerateResponseChatLlmResponse;
  chat?: SugarAiApi.ServiceGenerateResponseChatChat;
  stats?: SugarAiApi.ServiceGenerateResponseChatStats;
}
