/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateRequestMessagesItem {
  role: SugarAiApi.LiteServiceGenerateRequestMessagesItemRole;
  content: string;
}
