/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export type ServiceGenerateResponse =
  | SugarAiApi.ServiceGenerateResponseChat
  | "null";
