/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface ServiceGenerateResponseChat {
  id: string;
  environment: SugarAiApi.ServiceGenerateResponseChatEnvironment;
  version: string;
  prompt: string;
  completion?: string;
  latency: number;
  promptTokens: number;
  completionTokens: number;
  llmResponse?: SugarAiApi.ServiceGenerateResponseChatLlmResponse;
  promptVariables?: SugarAiApi.ServiceGenerateResponseChatPromptVariables;
  totalTokens: number;
  labelledState: SugarAiApi.ServiceGenerateResponseChatLabelledState;
  llmProvider: string;
  llmModel: string;
  llmModelType: SugarAiApi.ServiceGenerateResponseChatLlmModelType;
  chat?: SugarAiApi.ServiceGenerateResponseChatChat;
  createdAt: Date;
  updatedAt: Date;
}
