/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue {
  type: string;
  description: string;
  enum?: string[];
}
