/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface ServiceGenerateRequestSkillsItemFunctionParameters {
  type: string;
  properties: Record<
    string,
    SugarAiApi.ServiceGenerateRequestSkillsItemFunctionParametersPropertiesValue
  >;
  required: string[];
}
