/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGenerateRequestEnvironment = "DEV" | "PREVIEW" | "RELEASE";

export const ServiceGenerateRequestEnvironment = {
  Dev: "DEV",
  Preview: "PREVIEW",
  Release: "RELEASE",
} as const;
