/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface ServiceGenerateResponseCompletion {
  id: string;
  environment: SugarAiApi.ServiceGenerateResponseCompletionEnvironment;
  version: string;
  prompt: string;
  completion?: string;
  latency: number;
  promptTokens: number;
  completionTokens: number;
  llmResponse?: SugarAiApi.ServiceGenerateResponseCompletionLlmResponse;
  promptVariables?: SugarAiApi.ServiceGenerateResponseCompletionPromptVariables;
  totalTokens: number;
  labelledState: SugarAiApi.ServiceGenerateResponseCompletionLabelledState;
  llmProvider: string;
  llmModel: string;
  llmModelType: SugarAiApi.ServiceGenerateResponseCompletionLlmModelType;
  createdAt: Date;
  updatedAt: Date;
}
