import { z } from "zod";

export const allLanguages = {
  en: "English (English)",
  hi: "Hindi (हिन्दी)",
  ar: "Arabic (العربية)",
  ru: "Russian (Русский)",
  pt: "Portuguese (Português)",
  it: "Italian (Italiano)",
  ko: "Korean (한국어)",
  tr: "Turkish (Türkçe)",
  nl: "Dutch (Nederlands)",
  sv: "Swedish (Svenska)",
  pl: "Polish (Polski)",
  da: "Danish (Dansk)",
  fi: "Finnish (Suomi)",
  no: "Norwegian (Norsk)",
  el: "Greek (Ελληνικά)",
  he: "Hebrew (עברית)",
  cs: "Czech (Čeština)",
  hu: "Hungarian (Magyar)",
  th: "Thai (ไทย)",
  vi: "Vietnamese (Tiếng Việt)",
  es: "Spanish (Español)",
  fr: "French (Français)",
  de: "German (Deutsch)",
  zh: "Chinese (中文)",
  "en-US": "English (US)",
  "en-GB": "English (UK)",
  "fr-FR": "French (France)",
  "fr-CA": "French (Canada)",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexico)",
  "de-DE": "German (Germany)",
  "ja-JP": "Japanese (日本語)",
  "zh-CN": "Simplified Chinese (简体中文)",
  "zh-TW": "Traditional Chinese (繁體中文)",
  "hi-IN": "Hindi (India) (हिन्दी (भारत))",
  "bn-IN": "Bengali (India) (বাংলা (ভারত))",
  "ta-IN": "Tamil (India) (தமிழ் (இந்தியா))",
  "te-IN": "Telugu (India) (తెలుగు (భారతదేశం))",
  "mr-IN": "Marathi (India) (मराठी (भारत))",
  "gu-IN": "Gujarati (India) (ગુજરાતી (ભારત))",
  "kn-IN": "Kannada (India) (ಕನ್ನಡ (ಭಾರತ))",
  "ml-IN": "Malayalam (India) (മലയാളം (ഇന്ത്യ))",
  "pa-IN": "Punjabi (India) (ਪੰਜਾਬੀ (ਭਾਰਤ))",
  "or-IN": "Odia (India) (ଓଡ଼ିଆ (ଭାରତ))",
  "as-IN": "Assamese (India) (অসমীয়া (ভাৰত))",
  "ur-IN": "Urdu (India) (اردو (بھارت))",
  "ma-IN": "Maithili (India) (मैथिली (भारत))",
  "ks-IN": "Kashmiri (India) (کٲشُر (بھارت))",
  auto: "Automatic",
};

const languageCodes = Object.keys(allLanguages) as [keyof typeof allLanguages];

export const languageCode = z.enum(languageCodes);
export type LanguageCode = z.infer<typeof languageCode>;
