/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SugarAiApi from "../../../../api";
import * as core from "../../../../core";

export const MessageGenerateMessageRequestRole: core.serialization.Schema<
  serializers.MessageGenerateMessageRequestRole.Raw,
  SugarAiApi.MessageGenerateMessageRequestRole
> = core.serialization.enum_(["user", "assistant", "system"]);

export declare namespace MessageGenerateMessageRequestRole {
  type Raw = "user" | "assistant" | "system";
}
