/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         clientUserId: "clientUserId",
 *         metadata: {}
 *     }
 */
export interface FormSubmissionCreateSubmissionRequest {
  clientUserId: string;
  metadata: Record<string, unknown>;
}
