/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         clientUserId: "clientUserId"
 *     }
 */
export interface FormSubmissionCreateSubmissionRequest {
  clientUserId: string;
}
