/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

/**
 * @example
 *     {
 *         clientUserId: "clientUserId"
 *     }
 */
export interface FormSubmissionCreateSubmissionRequest {
  clientUserId: string;
  metadata: SugarAiApi.FormSubmissionCreateSubmissionRequestMetadata;
}
