/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         answer: "answer"
 *     }
 */
export interface FormSubmissionSubmitAnswerRequest {
  answer: string;
}
