/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         clientUserId: "clientUserId",
 *         answer: {},
 *         metadata: {}
 *     }
 */
export interface FormSubmissionSubmitAnswerRequest {
  clientUserId: string;
  answer: Record<string, unknown>;
  metadata: Record<string, unknown>;
}
