/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

/**
 * @example
 *     {
 *         clientUserId: "clientUserId",
 *         answer: {
 *             by: SugarAiApi.FormSubmissionSubmitAnswerRequestAnswerBy.Voice
 *         }
 *     }
 */
export interface FormSubmissionSubmitAnswerRequest {
  clientUserId: string;
  answer: SugarAiApi.FormSubmissionSubmitAnswerRequestAnswer;
  metadata: SugarAiApi.FormSubmissionSubmitAnswerRequestMetadata;
}
