/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class SugarAiApiTimeoutError extends Error {
  constructor() {
    super("Timeout");
    Object.setPrototypeOf(this, SugarAiApiTimeoutError.prototype);
  }
}
