/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../../..";

/**
 * @example
 *     {}
 */
export interface PromptGetPackagesRequest {
  userId?: string;
  visibility?: SugarAiApi.PromptGetPackagesRequestVisibility;
}
