/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SugarAiApiEnvironment = {
  Default: "http://localhost:3000/api",
} as const;

export type SugarAiApiEnvironment = typeof SugarAiApiEnvironment.Default;
