/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmbeddingLookupResponseItem {
  id: string;
  copilotId: string;
  identifier: string;
  chunk: string;
  doc: string;
  similarity: number;
}
