/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LiteServiceGenerateResponseChatRouterMode = "auto" | "manual";

export const LiteServiceGenerateResponseChatRouterMode = {
  Auto: "auto",
  Manual: "manual",
} as const;
