/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LiteServiceGenerateRequestRouterMode = "auto" | "manual";

export const LiteServiceGenerateRequestRouterMode = {
  Auto: "auto",
  Manual: "manual",
} as const;
