/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateRequestRouter {
  mode?: SugarAiApi.LiteServiceGenerateRequestRouterMode;
  threshold?: number;
}
