/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LiteServiceGenerateResponseChatStats =
  | string
  | number
  | boolean
  | unknown[]
  | Record<string, unknown>;
