/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateResponseChatRouter {
  mode: SugarAiApi.LiteServiceGenerateResponseChatRouterMode;
  match: string;
  prompt: string;
  score: number;
  threshold: number;
  text: string;
}
