/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface LiteServiceGenerateResponseChat {
  llmResponse?: SugarAiApi.LiteServiceGenerateResponseChatLlmResponse;
  chat?: SugarAiApi.LiteServiceGenerateResponseChatChat;
  stats?: SugarAiApi.LiteServiceGenerateResponseChatStats;
  router?: SugarAiApi.LiteServiceGenerateResponseChatRouter;
}
