/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LiteServiceGenerateRequestSkillChoice = "auto" | "none";

export const LiteServiceGenerateRequestSkillChoice = {
  Auto: "auto",
  None: "none",
} as const;
