/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGenerateResponseChatEnvironment =
  | "DEV"
  | "PREVIEW"
  | "RELEASE";

export const ServiceGenerateResponseChatEnvironment = {
  Dev: "DEV",
  Preview: "PREVIEW",
  Release: "RELEASE",
} as const;
