/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGenerateRequestSkillChoice = "auto" | "none";

export const ServiceGenerateRequestSkillChoice = {
  Auto: "auto",
  None: "none",
} as const;
