/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGenerateResponseChatLabelledState =
  | "UNLABELLED"
  | "SELECTED"
  | "REJECTED"
  | "NOTSURE";

export const ServiceGenerateResponseChatLabelledState = {
  Unlabelled: "UNLABELLED",
  Selected: "SELECTED",
  Rejected: "REJECTED",
  Notsure: "NOTSURE",
} as const;
