/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGenerateRequestRouterMode = "auto" | "manual";

export const ServiceGenerateRequestRouterMode = {
  Auto: "auto",
  Manual: "manual",
} as const;
