/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface PromptGetPackagesResponseItemCreatedAt {
  id: string;
  userId: string;
  name: string;
  visibility: SugarAiApi.PromptGetPackagesResponseItemCreatedAtVisibility;
  description: string;
  createdAt: Date;
  updatedAt: Date;
  templates?: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItem[];
}
