/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PromptGetPackagesResponseItemCreatedAtTemplatesItemModelType =
  | "TEXT2TEXT"
  | "TEXT2IMAGE"
  | "TEXT2CODE"
  | "IMAGE2IMAGE";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemModelType = {
  Text2Text: "TEXT2TEXT",
  Text2Image: "TEXT2IMAGE",
  Text2Code: "TEXT2CODE",
  Image2Image: "IMAGE2IMAGE",
} as const;
