/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SugarAiApi from "../../..";

export interface PromptGetPackagesResponseItemCreatedAtTemplatesItem {
  id: string;
  userId: string;
  promptPackageId: string;
  name: string;
  description: string;
  modelType: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemModelType;
  runMode: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemRunMode;
  releaseVersionId: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersionId;
  previewVersionId: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersionId;
  releaseVersion?: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemReleaseVersion;
  previewVersion?: SugarAiApi.PromptGetPackagesResponseItemCreatedAtTemplatesItemPreviewVersion;
  createdAt: Date;
  updatedAt: Date;
}
