/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PromptGetPackagesResponseItemCreatedAtVisibility =
  | "PUBLIC"
  | "PRIVATE";

export const PromptGetPackagesResponseItemCreatedAtVisibility = {
  Public: "PUBLIC",
  Private: "PRIVATE",
} as const;
