/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PromptGetPackagesRequestVisibility = "PUBLIC" | "PRIVATE";

export const PromptGetPackagesRequestVisibility = {
  Public: "PUBLIC",
  Private: "PRIVATE",
} as const;
