/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PromptGetPackagesResponseItemCreatedAtTemplatesItemRunMode =
  | "AUTHORISED_ONLY"
  | "LOGGEDIN_ONLY"
  | "ALL";

export const PromptGetPackagesResponseItemCreatedAtTemplatesItemRunMode = {
  AuthorisedOnly: "AUTHORISED_ONLY",
  LoggedinOnly: "LOGGEDIN_ONLY",
  All: "ALL",
} as const;
