/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const FormSubmissionSubmitAnswerRequest: core.serialization.Schema<
  serializers.FormSubmissionSubmitAnswerRequest.Raw,
  SugarAiApi.FormSubmissionSubmitAnswerRequest
> = core.serialization.object({
  clientUserId: core.serialization.string(),
  answer: core.serialization.lazyObject(
    async () =>
      (await import("../../../..")).FormSubmissionSubmitAnswerRequestAnswer,
  ),
  metadata: core.serialization.lazy(
    async () =>
      (await import("../../../..")).FormSubmissionSubmitAnswerRequestMetadata,
  ),
});

export declare namespace FormSubmissionSubmitAnswerRequest {
  interface Raw {
    clientUserId: string;
    answer: serializers.FormSubmissionSubmitAnswerRequestAnswer.Raw;
    metadata: serializers.FormSubmissionSubmitAnswerRequestMetadata.Raw;
  }
}
