/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const FormSubmissionCreateSubmissionRequest: core.serialization.Schema<
  serializers.FormSubmissionCreateSubmissionRequest.Raw,
  SugarAiApi.FormSubmissionCreateSubmissionRequest
> = core.serialization.object({
  clientUserId: core.serialization.string(),
  metadata: core.serialization.record(
    core.serialization.string(),
    core.serialization.unknown(),
  ),
});

export declare namespace FormSubmissionCreateSubmissionRequest {
  interface Raw {
    clientUserId: string;
    metadata: Record<string, unknown>;
  }
}
