/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SugarAiApi from "../../../../../api";
import * as core from "../../../../../core";

export const FormSubmissionSubmitAnswerRequest: core.serialization.Schema<
  serializers.FormSubmissionSubmitAnswerRequest.Raw,
  SugarAiApi.FormSubmissionSubmitAnswerRequest
> = core.serialization.object({
  clientUserId: core.serialization.string(),
  answer: core.serialization.record(
    core.serialization.string(),
    core.serialization.unknown(),
  ),
  metadata: core.serialization.record(
    core.serialization.string(),
    core.serialization.unknown(),
  ),
});

export declare namespace FormSubmissionSubmitAnswerRequest {
  interface Raw {
    clientUserId: string;
    answer: Record<string, unknown>;
    metadata: Record<string, unknown>;
  }
}
